USE [master]
GO

/****** Object:  Database [Cola]    Script Date: 24/10/2022 8:08:07 a. m. ******/
CREATE DATABASE [Cola]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cola', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSSQLSERVER\MSSQL\DATA\Cola.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cola_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSSQLSERVER\MSSQL\DATA\Cola_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cola].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cola] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cola] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cola] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cola] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cola] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cola] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cola] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cola] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cola] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cola] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cola] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cola] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cola] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cola] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cola] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cola] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cola] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cola] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cola] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cola] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cola] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cola] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cola] SET RECOVERY FULL 
GO

ALTER DATABASE [Cola] SET  MULTI_USER 
GO

ALTER DATABASE [Cola] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cola] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cola] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cola] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Cola] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Cola] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Cola] SET  READ_WRITE 
GO


