USE [Cola]
GO

/****** Object:  Table [dbo].[COLA_USUARIO]    Script Date: 23/10/2022 5:23:35 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COLA_USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[COLAID] [int] NULL,
	[ORDEN] [int] NULL,
	[STATUS] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COLA_USUARIO]  WITH CHECK ADD FOREIGN KEY([COLAID])
REFERENCES [dbo].[COLA] ([ID])
GO

ALTER TABLE [dbo].[COLA_USUARIO]  WITH CHECK ADD FOREIGN KEY([USERID])
REFERENCES [dbo].[USUARIO] ([ID])
GO



